//! ConVar metadata. `catalog/catalog.toml` is generated from
//! `research/data/convar_catalog.csv` plus `catalog/curated.toml` and embedded at build.

use std::collections::{BTreeMap, BTreeSet};
use std::sync::OnceLock;

use crate::preset::PresetId;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ApplyClass {
    Live,
    LiveCheat,
    Restart,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case", tag = "type")]
pub enum Kind {
    Bool,
    Int,
    Float,
    Enum { options: Vec<String> },
    String,
}

#[derive(
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Default,
    serde::Serialize,
    serde::Deserialize,
)]
#[serde(rename_all = "snake_case")]
pub enum Impact {
    High,
    Medium,
    Low,
    #[default]
    Unknown,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CatalogEntry {
    pub category: String,
    #[serde(flatten)]
    pub kind: Kind,
    pub range: Option<[f64; 2]>,
    pub step: Option<f64>,
    pub default: Option<String>,
    pub apply: ApplyClass,
    #[serde(default)]
    pub impact: Impact,
    #[serde(default)]
    pub denylist: bool,
    /// The engine flags it `gameinfo_cannot_override`: a `gameinfo.gi` line for it is ignored.
    #[serde(default)]
    pub gameinfo_ignored: bool,
    #[serde(default)]
    pub notes: String,
    /// Raw value per preset; a leading `//` means present but commented out.
    #[serde(default)]
    pub presets: BTreeMap<PresetId, String>,
}

#[derive(Clone, Debug, Default)]
pub struct Catalog {
    pub entries: BTreeMap<String, CatalogEntry>,
}

#[derive(Debug, thiserror::Error)]
pub enum CatalogError {
    #[error("csv: {0}")]
    Csv(#[from] csv::Error),
    #[error("toml: {0}")]
    TomlDe(#[from] toml::de::Error),
    #[error("toml: {0}")]
    TomlSer(#[from] toml::ser::Error),
    #[error("csv has no `{0}` column")]
    MissingColumn(String),
    #[error("curated.toml: {0}")]
    Curated(String),
}

impl Catalog {
    pub fn embedded() -> &'static Catalog {
        static CATALOG: OnceLock<Catalog> = OnceLock::new();
        CATALOG.get_or_init(|| {
            Catalog::from_toml(include_str!("../../../catalog/catalog.toml")).expect(
                "embedded catalog.toml is checked by embedded_catalog_matches_a_fresh_generate",
            )
        })
    }

    pub fn from_toml(text: &str) -> Result<Catalog, CatalogError> {
        Ok(Catalog {
            entries: toml::from_str(text)?,
        })
    }

    pub fn get(&self, name: &str) -> Option<&CatalogEntry> {
        self.entries.get(name)
    }

    /// Case-insensitive match on name, category and notes.
    pub fn search<'a>(
        &'a self,
        query: &'a str,
    ) -> impl Iterator<Item = (&'a str, &'a CatalogEntry)> + 'a {
        let query = query.to_lowercase();
        self.entries
            .iter()
            .filter(move |(name, e)| {
                [name.as_str(), e.category.as_str(), e.notes.as_str()]
                    .iter()
                    .any(|f| f.to_lowercase().contains(&query))
            })
            .map(|(name, e)| (name.as_str(), e))
    }

    pub fn categories(&self) -> Vec<&str> {
        let set: BTreeSet<&str> = self.entries.values().map(|e| e.category.as_str()).collect();
        set.into_iter().collect()
    }

    /// Unlisted convars are allowed but treated as `Restart`.
    pub fn apply_class(&self, name: &str) -> ApplyClass {
        self.get(name).map_or(ApplyClass::Restart, |e| e.apply)
    }

    pub fn is_denied(&self, name: &str) -> bool {
        self.get(name).is_some_and(|e| e.denylist)
    }

    pub fn is_gameinfo_ignored(&self, name: &str) -> bool {
        self.get(name).is_some_and(|e| e.gameinfo_ignored)
    }
}

/// Builds catalog.toml text from the research CSV and the hand-curated overlay.
pub fn generate(csv: &str, curated: &str) -> Result<String, CatalogError> {
    let mut entries = entries_from_csv(csv)?;
    let overlay: BTreeMap<String, Curated> = toml::from_str(curated)?;
    for (name, c) in overlay {
        let entry = entries
            .get_mut(&name)
            .ok_or_else(|| CatalogError::Curated(format!("{name} is not in the csv")))?;
        c.apply_to(entry)
            .map_err(|msg| CatalogError::Curated(format!("{name}: {msg}")))?;
    }
    Ok(format!(
        "# Generated by `cargo run -p dt-core --example gen_catalog`. Edit catalog/curated.toml instead.\n\n{}",
        toml::to_string(&entries)?
    ))
}

fn entries_from_csv(csv: &str) -> Result<BTreeMap<String, CatalogEntry>, CatalogError> {
    let mut reader = csv::Reader::from_reader(csv.as_bytes());
    let headers = reader.headers()?.clone();
    let col = |name: &str| {
        headers
            .iter()
            .position(|h| h == name)
            .ok_or_else(|| CatalogError::MissingColumn(name.to_string()))
    };
    let name_col = col("name")?;
    let apply_col = col("apply_class")?;
    let flags_col = col("flags")?;
    let default_col = col("engine_default")?;
    let desc_col = col("engine_description")?;
    let comment_col = col("preset_comment(first seen)")?;
    let preset_cols = crate::preset::all()
        .iter()
        .map(|p| Ok((p.id, col(p.id.key())?)))
        .collect::<Result<Vec<_>, CatalogError>>()?;

    let mut entries = BTreeMap::new();
    for record in reader.records() {
        let record = record?;
        let cell = |i: usize| record.get(i).unwrap_or("").trim();
        let name = cell(name_col);
        let meta = crate::gi::parse_comment_meta(cell(comment_col));
        let default = Some(cell(default_col))
            .filter(|d| !d.is_empty())
            .map(str::to_string)
            .or(meta.default);
        let presets: BTreeMap<PresetId, String> = preset_cols
            .iter()
            .filter(|(_, i)| !cell(*i).is_empty())
            .map(|(id, i)| (*id, cell(*i).to_string()))
            .collect();
        let kind = infer_kind(
            presets
                .values()
                .map(String::as_str)
                .chain(default.as_deref()),
        );
        let description = Some(cell(desc_col))
            .filter(|d| !d.is_empty())
            .unwrap_or(&meta.description);
        entries.insert(
            name.to_string(),
            CatalogEntry {
                category: category_for(name).to_string(),
                kind,
                range: None,
                step: None,
                default,
                apply: apply_class_from_csv(cell(apply_col)),
                impact: Impact::Unknown,
                denylist: false,
                gameinfo_ignored: cell(flags_col)
                    .split(',')
                    .any(|f| f.trim() == "gameinfo_cannot_override"),
                notes: description.split_whitespace().collect::<Vec<_>>().join(" "),
                presets,
            },
        );
    }
    Ok(entries)
}

fn apply_class_from_csv(raw: &str) -> ApplyClass {
    if raw == "live" {
        ApplyClass::Live
    } else if raw.starts_with("live w/ sv_cheats") {
        ApplyClass::LiveCheat
    } else {
        ApplyClass::Restart
    }
}

fn infer_kind<'a>(values: impl Iterator<Item = &'a str>) -> Kind {
    let values: Vec<&str> = values
        .map(|v| v.trim_start_matches("//").trim().trim_matches('"'))
        .filter(|v| !v.is_empty())
        .collect();
    let is_word_bool = |v: &str| v.eq_ignore_ascii_case("true") || v.eq_ignore_ascii_case("false");
    if values.is_empty() {
        Kind::String
    } else if values.iter().any(|v| is_word_bool(v))
        && values
            .iter()
            .all(|v| is_word_bool(v) || *v == "0" || *v == "1")
    {
        Kind::Bool
    } else if values.iter().all(|v| v.parse::<i64>().is_ok()) {
        Kind::Int
    } else if values.iter().all(|v| v.parse::<f64>().is_ok()) {
        Kind::Float
    } else {
        Kind::String
    }
}

/// First match wins, so more specific groups (outlines, shadows) sit above broad ones.
const CATEGORY_RULES: &[(&str, &[&str])] = &[
    ("Outlines & glow", &["outline", "glow", "see_thru"]),
    ("UI & Panorama", &["panorama", "pano_"]),
    ("Shadows", &["shadow", "csm_"]),
    (
        "Audio",
        &[
            "snd_",
            "audio_",
            "dsp_",
            "voice",
            "sos_",
            "soundsystem",
            "music_",
        ],
    ),
    ("AI & NPCs", &["ai_", "nav_", "npc", "trooper"]),
    (
        "Threads & jobs",
        &["thread", "parallel", "async", "_job", "multithread"],
    ),
    (
        "Particles & effects",
        &[
            "particle",
            "rope",
            "decal",
            "tracer",
            "impact",
            "splash",
            "fx_",
            "muzzleflash",
        ],
    ),
    (
        "Physics & animation",
        &[
            "phys", "ragdoll", "cloth", "ik_", "anim", "bone", "skel", "break", "violence",
            "morph", "flex", "skinning",
        ],
    ),
    ("World detail", &["grass", "clutter", "hair", "wind"]),
    (
        "Render distance & LOD",
        &[
            "farz",
            "nearz",
            "lod",
            "fade",
            "maxdist",
            "cull",
            "mapextents",
            "draw3dskybox",
        ],
    ),
    (
        "Lighting & post-processing",
        &[
            "lb_",
            "light",
            "ambient",
            "ssao",
            "ao_",
            "bloom",
            "tonemap",
            "fog",
            "sun",
            "envmap",
            "cubemap",
            "distancefield",
            "colorcorrection",
            "colcorrection",
            "depthoffield",
            "depth_of_field",
            "postprocess",
            "gamma",
            "multiscattering",
            "rtx_",
        ],
    ),
    ("Textures & shaders", &["texture", "mat_", "shader", "mip"]),
    (
        "Resolution & upscaling",
        &[
            "antialiasing",
            "upscaling",
            "fsr",
            "viewportscale",
            "aspectratio",
        ],
    ),
    (
        "UI & Panorama",
        &[
            "hud",
            "unit_status",
            "damage",
            "minimap",
            "caption",
            "toast",
            "ping",
            "chat_wheel",
            "crosshair",
            "portrait",
            "survey",
            "dashboard",
        ],
    ),
    (
        "Network & prediction",
        &[
            "net_",
            "interp",
            "updaterate",
            "tickpacket",
            "clock",
            "resend",
            "sv_",
            "cq_",
            "pred",
            "usercmd",
            "pvs",
            "subtick",
            "cl_smooth",
        ],
    ),
    (
        "Frame rate & latency",
        &[
            "fps",
            "engine_",
            "latency",
            "present",
            "frame_sync",
            "battery",
            "priority_boost",
            "render_frames",
            "_level",
        ],
    ),
    (
        "Camera & view",
        &[
            "camera",
            "fov",
            "cam_",
            "viewmodel",
            "first_person",
            "shake",
        ],
    ),
    (
        "Input",
        &["rawinput", "raw_keyboard", "joystick", "inputhandler"],
    ),
    (
        "Render pipeline",
        &[
            "sc_",
            "r_draw",
            "zprepass",
            "zreject",
            "vulkan",
            "dx11",
            "portal",
            "skybox",
            "pixelvisibility",
            "r_opaque",
            "r_translucent",
            "overlays",
            "occlusion",
            "cloak",
            "clip_sphere",
            "depth_prepass",
            "sceneobject",
        ],
    ),
];

fn category_for(name: &str) -> &'static str {
    let lower = name.to_ascii_lowercase();
    CATEGORY_RULES
        .iter()
        .find(|(_, needles)| needles.iter().any(|n| lower.contains(n)))
        .map_or("Advanced", |(category, _)| category)
}

#[derive(serde::Deserialize)]
#[serde(rename_all = "snake_case")]
enum CuratedKind {
    Bool,
    Int,
    Float,
    Enum,
    String,
}

/// A per-name overlay in curated.toml; every field is optional and replaces the generated one.
#[derive(serde::Deserialize)]
#[serde(deny_unknown_fields)]
struct Curated {
    category: Option<String>,
    #[serde(rename = "type")]
    kind: Option<CuratedKind>,
    options: Option<Vec<String>>,
    range: Option<[f64; 2]>,
    step: Option<f64>,
    impact: Option<Impact>,
    denylist: Option<bool>,
    notes: Option<String>,
}

impl Curated {
    fn apply_to(self, entry: &mut CatalogEntry) -> Result<(), &'static str> {
        match (self.kind, self.options) {
            (Some(CuratedKind::Enum), Some(options)) if !options.is_empty() => {
                entry.kind = Kind::Enum { options }
            }
            (Some(CuratedKind::Enum), _) => return Err("type = \"enum\" needs non-empty options"),
            (_, Some(_)) => return Err("options only apply to type = \"enum\""),
            (Some(CuratedKind::Bool), None) => entry.kind = Kind::Bool,
            (Some(CuratedKind::Int), None) => entry.kind = Kind::Int,
            (Some(CuratedKind::Float), None) => entry.kind = Kind::Float,
            (Some(CuratedKind::String), None) => entry.kind = Kind::String,
            (None, None) => {}
        }
        if let Some(category) = self.category {
            entry.category = category;
        }
        entry.range = self.range.or(entry.range);
        entry.step = self.step.or(entry.step);
        entry.impact = self.impact.unwrap_or(entry.impact);
        entry.denylist = self.denylist.unwrap_or(entry.denylist);
        if let Some(notes) = self.notes {
            entry.notes = notes;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const CSV: &str = include_str!("../../../research/data/convar_catalog.csv");
    const CURATED: &str = include_str!("../../../catalog/curated.toml");

    fn generated(curated: &str) -> Catalog {
        Catalog::from_toml(&generate(CSV, curated).unwrap()).unwrap()
    }

    #[test]
    fn generate_emits_one_entry_per_csv_row() {
        assert_eq!(generated("").entries.len(), 772);
    }

    #[test]
    fn apply_class_follows_csv_flags() {
        let c = generated("");
        assert_eq!(c.apply_class("fps_max"), ApplyClass::Live);
        assert_eq!(c.apply_class("r_farz"), ApplyClass::LiveCheat);
        assert_eq!(
            c.apply_class("r_citadel_shadow_quality"),
            ApplyClass::Restart,
            "devonly is gameinfo-only"
        );
        assert_eq!(
            c.apply_class("ai_disable"),
            ApplyClass::Restart,
            "unknown flags are treated as restart"
        );
    }

    #[test]
    fn gameinfo_ignored_follows_the_csv_flag() {
        let c = generated("");
        assert!(c.is_gameinfo_ignored("r_shadows"));
        assert!(c.is_gameinfo_ignored("r_citadel_npr_outlines"));
        assert!(!c.is_gameinfo_ignored("r_citadel_shadow_quality"));
        assert!(!c.is_gameinfo_ignored("not_a_convar"));
        assert_eq!(
            c.entries.values().filter(|e| e.gameinfo_ignored).count(),
            37
        );
    }

    #[test]
    fn kind_is_inferred_from_values() {
        let c = generated("");
        assert_eq!(
            c.get("r_ssao").unwrap().kind,
            Kind::Bool,
            "true default with 0 in presets"
        );
        assert_eq!(c.get("fps_max").unwrap().kind, Kind::Int);
        assert_eq!(
            c.get("sc_screen_size_lod_scale_override").unwrap().kind,
            Kind::Float
        );
        assert_eq!(
            c.get("r_particle_max_draw_distance").unwrap().kind,
            Kind::Float,
            "1e+06 default"
        );
    }

    #[test]
    fn default_prefers_engine_then_comment() {
        let c = generated("");
        assert_eq!(c.get("fps_max").unwrap().default.as_deref(), Some("400"));
        assert_eq!(
            c.get("ai_disable").unwrap().default.as_deref(),
            Some("0"),
            "from [def: \"0\"]"
        );
        assert_eq!(c.get("ai_async_queue_max_jobs").unwrap().default, None);
    }

    #[test]
    fn presets_and_notes_come_from_the_csv() {
        let c = generated("");
        let farz = c.get("r_farz").unwrap();
        assert_eq!(
            farz.presets.get(&PresetId::KaizMinspec).map(String::as_str),
            Some("4500")
        );
        assert_eq!(
            farz.presets.get(&PresetId::Vanilla),
            None,
            "empty preset cells are skipped"
        );
        assert_eq!(
            c.get("ai_disable")
                .unwrap()
                .presets
                .get(&PresetId::Sqooky)
                .map(String::as_str),
            Some("//1"),
            "commented values keep their //"
        );
        assert!(
            farz.notes.starts_with("Override the far clipping plane."),
            "{}",
            farz.notes
        );
        assert!(
            c.get("ai_disable")
                .unwrap()
                .notes
                .starts_with("Both of these commands")
        );
    }

    #[test]
    fn category_is_inferred_from_name() {
        let c = generated("");
        assert_eq!(c.get("csm_max_visible_dist").unwrap().category, "Shadows");
        assert_eq!(c.get("panorama_max_fps").unwrap().category, "UI & Panorama");
        assert_eq!(
            c.get("r_particle_max_detail_level").unwrap().category,
            "Particles & effects"
        );
        assert_eq!(
            c.get("this_is_an_example_comment").unwrap().category,
            "Advanced"
        );
    }

    #[test]
    fn curated_overrides_win() {
        let curated = r#"
            [r_farz]
            category = "Custom"
            range = [2000, 16000]
            step = 500
            impact = "high"
            notes = "curated note"
            [fps_max]
            type = "enum"
            options = ["0", "60"]
            [citadel_player_outline_enemies]
            denylist = true
        "#;
        let c = generated(curated);
        let farz = c.get("r_farz").unwrap();
        assert_eq!(farz.category, "Custom");
        assert_eq!(farz.range, Some([2000.0, 16000.0]));
        assert_eq!(farz.step, Some(500.0));
        assert_eq!(farz.impact, Impact::High);
        assert_eq!(farz.notes, "curated note");
        assert_eq!(
            farz.apply,
            ApplyClass::LiveCheat,
            "fields not in the overlay stay generated"
        );
        assert_eq!(
            c.get("fps_max").unwrap().kind,
            Kind::Enum {
                options: vec!["0".into(), "60".into()]
            }
        );
        assert!(c.is_denied("citadel_player_outline_enemies"));
        assert!(!c.is_denied("r_farz"));
    }

    #[test]
    fn curated_rejects_unknown_names_and_fields() {
        assert!(
            generate(CSV, "[r_farzz]\nimpact = \"high\"").is_err(),
            "typo in name"
        );
        assert!(
            generate(CSV, "[r_farz]\nimpakt = \"high\"").is_err(),
            "typo in field"
        );
        assert!(
            generate(CSV, "[r_farz]\ntype = \"enum\"").is_err(),
            "enum without options"
        );
    }

    #[test]
    fn committed_curated_marks_competitive_info_and_perf_convars() {
        let c = generated(CURATED);
        for name in [
            "citadel_player_outline_enemies",
            "citadel_unit_status_allies_see_thru_walls",
            "sv_force_transmit_players",
            "citadel_player_outline_fade_range_min",
            "citadel_player_outline_fade_range_max",
            "r_citadel_selection_outline2_fade_pow",
        ] {
            assert!(c.is_denied(name), "{name} should be denylisted");
        }
        assert!(
            !c.is_denied("citadel_camera_hero_fov"),
            "FOV is a normal setting"
        );
        assert!(
            !c.is_denied("citadel_damage_indicator_radius"),
            "your own hit-direction marker shows nothing about other players"
        );
        let rated = c
            .entries
            .values()
            .filter(|e| e.impact != Impact::Unknown)
            .count();
        assert!(rated >= 55, "only {rated} convars carry an impact rating");
    }

    #[test]
    fn embedded_catalog_matches_a_fresh_generate() {
        let fresh = generate(CSV, CURATED).unwrap();
        assert!(
            include_str!("../../../catalog/catalog.toml") == fresh,
            "catalog/catalog.toml is stale; run `cargo run -p dt-core --example gen_catalog`"
        );
        assert_eq!(Catalog::embedded().entries.len(), 772);
    }

    #[test]
    fn search_is_case_insensitive_over_name_category_and_notes() {
        let c = generated(CURATED);
        let names = |q| c.search(q).map(|(n, _)| n.to_string()).collect::<Vec<_>>();
        assert!(names("R_FARZ").contains(&"r_farz".to_string()));
        assert!(
            names("shadows").contains(&"csm_max_visible_dist".to_string()),
            "category match"
        );
        assert!(
            names("FAR CLIP plane").contains(&"r_farz".to_string()),
            "notes match"
        );
        assert!(names("zzzz-no-such-thing").is_empty());
    }

    #[test]
    fn categories_are_sorted_and_unique() {
        let c = generated(CURATED);
        let cats = c.categories();
        let mut sorted = cats.clone();
        sorted.sort();
        sorted.dedup();
        assert_eq!(cats, sorted);
        assert!(cats.contains(&"Shadows") && cats.contains(&"Advanced"));
    }
}
