//! HUD ConVars (crosshair, minimap icons, overhead bars, damage numbers).
//! Data lives in `catalog/hud.toml`, generated by `examples/gen_hud_catalog.rs`.
//! Apply class is the most conservative of the two dumps: devonly in either
//! `cvarlist.txt` or `convars.txt` means restart.

use std::collections::BTreeMap;

use super::elements::ElementId;
use crate::catalog::CatalogEntry;

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct HudConVar {
    /// None for HUD-wide ones (`citadel_hud_visible`).
    pub element: Option<ElementId>,
    #[serde(flatten)]
    pub entry: CatalogEntry,
}

pub fn embedded() -> &'static BTreeMap<String, HudConVar> {
    todo!()
}

pub fn for_element(id: ElementId) -> impl Iterator<Item = (&'static str, &'static HudConVar)> {
    embedded().iter().filter(move |(_, c)| c.element == Some(id)).map(|(n, c)| (n.as_str(), c))
}
